### ISSUE TITLE
DeepInterestNetwork opens

### ISSUE THREAD

**Issue by sergeigofman** [alibaba/ai-matrix#3]
lt looks like in DeepInterestNetwork, provided infer.py script does not reflect the typical expected inference usage model: infer.py invokes model.eval(), which basically is given two items - one (i) for which the expected correct answer is "positive" ("expected interaction") and another one (j), for which the expected correct answer is "negative" ("expected no interaction"). In practice, though, I believe that more representative inference use case is covered by model.test() method, in which the entire set of items is checked for interactions with a specific user. I would like to confirm that this is correct, because if it is, I have identified potential issues within model.test() implementation, which I would raise as a separate issue.

**Comment by zhougr1993** [comment]
Your question is appreciated. I have made explanation in https://github.com/zhougr1993/DeepInterestNetwork/issues/7. It is a issues. The implementation of inference is wrong. The code of the calculation of several evaluation of the experiments in paper is correct. But the calculation of prediction for whole items in model.test() is wrong.

**Comment by sergeigofman** [comment]
@zhougr1993 Thanks for clarifying and confirming my suspicions.
@zhougr1993 @frank-wei @xulingjie Since the ai-matrix benchmark is about inference, I believe, the inference path of DeepInterestNetwork benchmark (the real world inference scenario, like 1 user vs. many or all available items) must be fixed, and made the default for performance measurement. Can you please confirm that this is what you are going to do?

**Comment by xulingjie** [comment]
@sergeigofman thanks for the post. We will work on the fix soon.

**Comment by frank-wei** [comment]
The problem has been fixed in the current version.
