### ISSUE TITLE
DeepInterestNetwork: inconsistant between code and result

### ISSUE THREAD

**Issue by imcarsonliao** [alibaba/ai-matrix#5]
Regarding to deepinterestnetwork, training use batch size of 256,512,1024 and inference use batch size of 1,  32, 64. However, the benchmark result shows 256, 512, 1024 for inference. Is there anything wrong? please help confirm it.

**Comment by frank-wei** [comment]
@imcarsonliao  there is a typo there. We have fixed that. Please check our new results from version 1.0.2.
